import "./globals.css";
import { Inter } from "next/font/google";
import CeramicProvider from "./providers/CeramicProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <CeramicProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </CeramicProvider>
  );
}
